server:
  port : 8082
  error:
    include-stacktrace: never
spring:
  rabbitmq:
    host: localhost
    port: 5672
    password: guest
    username: guest
    queue: bip.queue
    routingkey: bip.routingkey