server:
  port : 8082
  error:
    include-stacktrace: never
spring:
  data:
    mongodb:
      uri: mongodb+srv://<username>:<pwd>@<cluster>.mongodb.net/mygrocerylist
      database: bip
      port: 27017
      host: localhost
      username: admin
      password: password
  rabbitmq:
    host: localhost
    port: 5672
    password: guest
    username: guest
    queue: bip.queue
    routingkey: bip.routingkey
  elrond:
    client:
      gateway: devnet
      readTimeoutMillis: 10000
      writeTimeoutMillis: 10000